[workspace.package]
description = "A simple tool for creating modern online books in pure typst."
authors = ["typst-book Developers"]
version = "0.1.2"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"
homepage = "https://github.com/Myriad-Dreamin/typst-book"
repository = "https://github.com/Myriad-Dreamin/typst-book"


[workspace]
resolver = "2"
members = ["cli", "tools/build-from-source"]

[profile.release]
debug = true

[profile.release-stripped]
inherits = "release"
debug = false
strip = true

[workspace.dependencies]

typst = "0.10.0"
typst-ts-svg-exporter = { version = "0.4.2-rc4", features = [
    "experimental-ligature",
] }
typst-ts-core = "0.4.2-rc4"
typst-ts-compiler = "0.4.2-rc4"

handlebars = "4.5"

# general
anyhow = "1"
comemo = "0.3.1"
tokio = { version = "1.35", features = ["full"] }

# cryptography and processing
serde = { version = "1.0.193" }
serde_json = "1.0.108"
toml = "0.8"

# web
warp = { version = "0.3", features = ["compression"] }

# cli
clap = { version = "4.4", features = ["derive", "env", "unicode", "wrap_help"] }
clap_complete = "4.4"
clap_complete_fig = "4.4"

# logging and tracing
env_logger = "0.10.1"
log = "0.4.20"

# misc
vergen = { version = "7.5.1", features = ["build", "cargo", "git", "rustc"] }
include_dir = "0.7.3"
pathdiff = "0.2.1"

[patch.crates-io]
typst = { git = "https://github.com/Myriad-Dreamin/typst.git", branch = "typst.ts-v0.11.0-content-hint" }
typst-syntax = { git = "https://github.com/Myriad-Dreamin/typst.git", branch = "typst.ts-v0.11.0-content-hint" }
typst-ts-svg-exporter = { git = "https://github.com/Myriad-Dreamin/typst.ts", branch = "book-exp", package = "typst-ts-svg-exporter" }
typst-ts-core = { git = "https://github.com/Myriad-Dreamin/typst.ts", branch = "book-exp", package = "typst-ts-core" }
typst-ts-compiler = { git = "https://github.com/Myriad-Dreamin/typst.ts", branch = "book-exp", package = "typst-ts-compiler" }

# typst = { path = "../../../typst/crates/typst" }
# typst-syntax = { path = "../../../typst/crates/typst-syntax" }
# typst-ts-svg-exporter = { path = "../../exporter/svg" }
# typst-ts-compiler = { path = "../../compiler" }
# typst-ts-core = { path = "../../core" }
